version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    env_file:
      - .env
    command: streamlit run app.py
